version: "3"

services:
  symfony:
    build:
      context: ./
      dockerfile: ./Docker/Symfony/Dockerfile
    container_name: web_app_symfony
    environment:
      UID: 1000
      GID: 1000
    volumes:
      - ./:/home/symfonyuser/app
    ports:
      - "80:8000"
    links:
      - database
      - mailer
    depends_on:
      - database
  node:
    build:
      context: ./
      dockerfile: ./Docker/Node/Dockerfile
    volumes:
      - ./:/home/node/app
    container_name: web_app_node
    depends_on:
      - symfony
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql
    expose:
      - "5432"
  mailer:
    image: schickling/mailcatcher
    expose:
      - 1025
      - 1080
    ports: ["5080:1080"]

volumes:
  pg_data:


